### ISSUE TITLE
联锁竞赛关卡无法识别

### ISSUE THREAD

**Issue by Teddypyf** [AgainstEntropy/PRTS#1]
联锁竞赛关卡无法识别开始行动按钮,目前认为是脚本中没有对应颜色导致无法识别.
(可以试试改一下代理线程下关于深粉色的那段,那段是为了适配火蓝之心活动)

**Comment by Teddypyf** [comment]
尝试修改颜色识别代码,通过修改检测模式下的颜色码实现了对联锁竞赛的开始行动按钮识别.
颜色码由原先的#0095d6改为#1559be

**Comment by AgainstEntropy** [comment]
已经更新了v0.5.7！这次肯定可以识别活动关卡了了~
我是去年2月入坑的，之前并不知道火蓝之心的开始按钮居然是那个粉色hhh你这么一提醒我就明白了
v0.5.5只补充了收基建和信用的功能，刚好鹰角新增了自动收任务奖励的功能，下个版本代码就可以更简练一点了！
